version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/git-taiwa"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/simple-note-cli"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/simple-todo-cli"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/text-util"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/wc"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/fake-weather"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/time"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/sisou-cli"
    schedule:
      interval: "daily"
