version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/calc"
    schedule:
      interval: "daily"
    package-manager: "bun"

  - package-ecosystem: "npm"
    directory: "/fake-weather"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/gat"
    schedule:
      interval: "daily"
    package-manager: "bun"

  - package-ecosystem: "npm"
    directory: "/git-standup"
    schedule:
      interval: "daily"
    package-manager: "pnpm"

  - package-ecosystem: "npm"
    directory: "/git-taiwa"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/janken"
    schedule:
      interval: "daily"
    package-manager: "bun"

  - package-ecosystem: "npm"
    directory: "/nix-installed-pkgs"
    schedule:
      interval: "daily"
    package-manager: "bun"

  - package-ecosystem: "npm"
    directory: "/pkg-why"
    schedule:
      interval: "daily"
    package-manager: "bun"

  - package-ecosystem: "npm"
    directory: "/riaju-cli"
    schedule:
      interval: "daily"
    package-manager: "pnpm"

  - package-ecosystem: "npm"
    directory: "/shell-list"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/simple-note-cli"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/simple-todo-cli"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/sisou-cli"
    schedule:
      interval: "daily"
    package-manager: "pnpm"

  - package-ecosystem: "npm"
    directory: "/text-util"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/time"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/wc"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/whoami"
    schedule:
      interval: "daily"
